version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - backend

  backend:
    image: node:20-alpine
    container_name: node_backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - '3000:3000'
    depends_on:
      - backend_db
    command: sh -c "npm install && node index.js"

  backend_db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" 
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - backend_db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgadmin_data:
